#Use this file to create an environment using:
#conda env create -f requirements.yaml

name: ecohub 
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.2.3
  - biopython=1.81
  - requests=2.31.0
  - pyyaml=6.0.2
  - pip=21.3.1
  - ipykernel